name: Build and Save Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-save:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm install

      - name: Build Docker image
        # 使用多阶段构建，只将最终的运行时依赖项包含在最终镜像中
        run: |
          docker build -t oblatum_art_astro:latest -f Dockerfile .

      # docker push pzhown/oblatum_art_astro:latest

      - name: Save Docker image
        # 使用 --compress 选项压缩镜像
        run: docker save --compress oblatum_art_astro:latest > oblatum_art_astro.tar

      - name: Upload Docker image
        uses: actions/upload-artifact@v2
        with:
          name: oblatum_art_astro
          path: oblatum_art_astro.tar

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Copy Docker image to server
        run: scp oblatum_art_astro.tar ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/home/oblatum/oblatum_art_astro.tar
