name: Build and Save Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-save:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm install

      - name: Build Docker image
        run: docker build -t oblatum_art_astro:latest .

      - name: Save Docker image
        run: docker save oblatum_art_astro:latest > oblatum_art_astro.tar

      # 将镜像导出到Github actions的artifacts中
      - name: Upload Docker image
        uses: actions/upload-artifact@v2
        with:
          name: oblatum_art_astro

      # - name: Login to Docker registry
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      #     server: ${{ secrets.DOCKER_REGISTRY }}

      # - name: Push Docker image
      #   run: docker push ${{ secrets.DOCKER_REGISTRY }}/oblatum_art_astro:latest

      # - name: Run Docker image on server
      #   run: |
      #     ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "docker run -d -p 80:80 ${{ secrets.DOCKER_REGISTRY }}/oblatum_art_astro:latest"
