name: Build and Save Docker Image

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: Install
        run: npm install -g pnpm
      - run: pnpm i
      - run: pnpm run build

  build-and-save:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: Install
        run: npm install -g pnpm

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v3
        id: buildx

      - run: echo ${{ secrets.DOCKER_KEY }} | docker login ghcr.io --username phanatic --password-stdin

      - name: build and publish ghcr.io docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          builder: ${{ steps.buildx.outputs.name }}
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/oblatum/oblatum-web-astro/oblatum-web-astro:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
